### ISSUE TITLE
Feature: Output multiple formats within one `time` element

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-date#137]
`o-date` by default replaces all `time` element children with the formatted date. 
However if there is a child element with the class `o-date__printer` `o-date`
will put the formatted date within the `o-date__printer` element and leave other 
child elements intact. 

This is useful to decorate a time with other information. One such usecase which has recently
arisen is to show a relative time followed by the absolute time:

```html
<time data-o-component="o-date" class="o-date" data-o-date-format="time-ago-abbreviated" datetime="2020-07-18T19:01:05.033Z" data-o-date-format="time-ago-abbreviated">
    <span class="o-date__printer">
			<!-- render the abbreviated, relative time ago here -->
		</span>
		<!-- always include the exact time -->
    <span>14:36</span>
</time>
```

However in the above example we also want the exact time `14:36` to be formatted as well
so that it is localised correctly.

## proposed solution

- Deprecate `o-date__printer`
- Render a date within any child that has the `data-o-date-format` attribute

*example 1: render two date formats within one time element*

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}">
    <span data-o-date-format="time-ago-abbreviated">
        <!-- render the abbreviated, relative time ago here -->
    </span>
    <span data-o-date-format="h:mm">
        <!-- render the absolute time here -->
    </span>
</time>
```

*example 2: render one date format within one time element, with child content*

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}">
    <span>time since thing:</span>
    <span data-o-date-format="time-ago-abbreviated">
        <!-- render the abbreviated, relative time ago here -->
    </span>
</time>
```

*example 3: second way to render one date format within one time element, with child content*

In this example the value of `data-o-date-format` is not set on the child so the 
`data-o-date-format` attribute on the parent `time` element will be used.

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}" data-o-date-format="time-ago-abbreviated">
    <span>time since thing:</span>
    <span data-o-date-format>
        <!-- render the abbreviated, relative time ago here -->
    </span>
</time>
```

**Comment by notlee** [comment]
The Content Innovation team are looking to use this

**Comment by notlee** [comment]
Updated the proposed solution to give more examples. I think example 3 is a bit confusing. I'm leaning toward replacing `o-date__printer` with a data attribute instead (to indicate use by js over just styling purposes) and allowing it to be used with the format attribute:

*example 1: render two date formats within one time element*

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}">
    <span data-o-date-printer data-o-date-format="time-ago-abbreviated">
        <!-- render the abbreviated, relative time ago here -->
    </span>
    <span data-o-date-printer data-o-date-format="h:mm">
        <!-- render the absolute time here -->
    </span>
</time>
```

*example 2: render one date format within one time element, with child content*

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}">
    <span>time since thing:</span>
    <span data-o-date-printer data-o-date-format="time-ago-abbreviated">
        <!-- render the abbreviated, relative time ago here -->
    </span>
</time>
```

*example 3: second way to render one date format within one time element, with child content*

In this example the value of `data-o-date-format` is not set on the child so the 
`data-o-date-format` attribute on the parent `time` element will be used.

```html
<time data-o-component="o-date" class="o-date" datetime="{{iso8601String}}" data-o-date-format="time-ago-abbreviated">
    <span>time since thing:</span>
    <span data-o-date-printer>
        <!-- render the abbreviated, relative time ago here -->
    </span>
</time>
```

**Comment by JakeChampion** [comment]
Good idea Lee, let's do it 👍

**Comment by JakeChampion** [comment]
To confirm, the proposal I think we should do, is your second one:
>I'm leaning toward replacing o-date__printer with a data attribute instead (to indicate use by js over just styling purposes) and allowing it to be used with the format attribute
👍
