### ISSUE TITLE
Dates don't work in Desktop Safari Mac

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-date#31]
Compare this in Chrome vs. Safari
http://build.origami.ft.com/files/o-date@1.1.0/demos/declarative.html

![screen shot 2015-01-20 at 17 32 02](https://cloud.githubusercontent.com/assets/825088/5822243/441dffe8-a0ca-11e4-82f7-ce6d3a875299.png)

![screen shot 2015-01-20 at 17 32 13](https://cloud.githubusercontent.com/assets/825088/5822245/49998ed8-a0ca-11e4-910d-c6150cdf3db6.png)

**Comment by matthew-andrews** [comment]
[declarative only]

**Comment by kaelig** [comment]
Thanks, I've found the issue, I'll update it.

**Comment by matthew-andrews** [comment]
ah me too :)
