### ISSUE TITLE
Not really a bug in o-date but something to be aware of…

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-date#34]
Safari (Desktop) is super fussy about the format of date strings.

Works:-

```
"2014-07-31T23:00:00.000Z" // (new Date("2015-01-20T10:46:02Z")).toString();
"2014-07-31T23:00:00.000+00:00" // (new Date("2015-01-20T10:46:02+00:00")).toString();
```

Doesn't work:-
```
"2014-07-31T23:00:00.000+0000" // (new Date("2015-01-20T10:46:02+0000")).toString();
```

I wonder whether we should:-
1. do nothing
2. document it
3. ‘fix’ this with a workaround in o-date
4. ‘fix’ this with a polyfill in the polyfill service (not sure if this is possible)

I prefer option 1.

**Comment by matthew-andrews** [comment]
Same is true for IE9

**Comment by onishiweb** [comment]
I think it would be worth putting this into the documentation as just a heads up to people.
