### ISSUE TITLE
Extract the date-formatting utilities to a library

### ISSUE THREAD

**Issue by chee** [Financial-Times/o-date#94]
at the moment this origami component is special
it's the only o-component used on the server

there is a [section in the spec](https://origami-test.ft.com/spec/v1/components/#isomorphic-components) that exists only to make its specialness ok
there is [special code in occ](https://github.com/Financial-Times/origami-component-converter/blob/8d8ee9721fbbfa28f0de148b16ce26fd26c249e2/lib/npm.js#L31) to make it continue to work on npm

instead of making this component special, let's remove server-side support from origami components and pull the parts of this that are used on the server (the date formatting) out to a library

then apps and o-date can both use that library.

```
–——

 .
/ \
```

**Comment by JakeChampion** [comment]
Resolved via https://github.com/Financial-Times/o-date/pull/98
